version: "3"
services:

  redis:
    image: "redis:alpine"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: atlan
  web:
    build: .
    ports:
      - "8000:8000"
# Names our volume
#volumes:
 # my-db: